export const RULES = `rules:
- DOMAIN-SUFFIX,acl4.ssr,DIRECT
- DOMAIN-SUFFIX,ip6-localhost,DIRECT
- DOMAIN-SUFFIX,ip6-loopback,DIRECT
- DOMAIN-SUFFIX,lan,DIRECT
- DOMAIN-SUFFIX,local,DIRECT
- DOMAIN-SUFFIX,localhost,DIRECT
- IP-CIDR,0.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
- IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
- IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
- IP-CIDR,198.18.0.0/16,DIRECT,no-resolve
- IP-CIDR,224.0.0.0/4,DIRECT,no-resolve
- IP-CIDR6,::1/128,DIRECT,no-resolve
- IP-CIDR6,fc00::/7,DIRECT,no-resolve
- IP-CIDR6,fe80::/10,DIRECT,no-resolve
- IP-CIDR6,fd00::/8,DIRECT,no-resolve
- DOMAIN,instant.arubanetworks.com,DIRECT
- DOMAIN,setmeup.arubanetworks.com,DIRECT
- DOMAIN,router.asus.com,DIRECT
- DOMAIN,www.asusrouter.com,DIRECT
- DOMAIN-SUFFIX,hiwifi.com,DIRECT
- DOMAIN-SUFFIX,leike.cc,DIRECT
- DOMAIN-SUFFIX,miwifi.com,DIRECT
- DOMAIN-SUFFIX,my.router,DIRECT
- DOMAIN-SUFFIX,p.to,DIRECT
- DOMAIN-SUFFIX,peiluyou.com,DIRECT
- DOMAIN-SUFFIX,phicomm.me,DIRECT
- DOMAIN-SUFFIX,router.ctc,DIRECT
- DOMAIN-SUFFIX,routerlogin.com,DIRECT
- DOMAIN-SUFFIX,tendawifi.com,DIRECT
- DOMAIN-SUFFIX,zte.home,DIRECT
- DOMAIN-SUFFIX,tplogin.cn,DIRECT
- DOMAIN-SUFFIX,wifi.cmcc,DIRECT
- DOMAIN-SUFFIX,kkgithub.com,DIRECT
- DOMAIN-SUFFIX,bgithub.xyz,DIRECT
- DOMAIN-SUFFIX,dgithub.xyz,DIRECT
- DOMAIN-SUFFIX,fgithub.xyz,DIRECT
- DOMAIN-SUFFIX,hgithub.xyz,DIRECT
- DOMAIN-SUFFIX,igithub.xyz,DIRECT
- DOMAIN-SUFFIX,jgithub.xyz,DIRECT
- DOMAIN-SUFFIX,lgithub.xyz,DIRECT
- DOMAIN-SUFFIX,4git.xyz,DIRECT
- DOMAIN-SUFFIX,5git.xyz,DIRECT
- DOMAIN-SUFFIX,6git.xyz,DIRECT
- DOMAIN-SUFFIX,mgithub.xyz,DIRECT
- DOMAIN-SUFFIX,ngithub.xyz,DIRECT
- DOMAIN-SUFFIX,ogithub.xyz,DIRECT
- DOMAIN-SUFFIX,pgithub.xyz,DIRECT
- DOMAIN,hub.whtrys.space,DIRECT
- DOMAIN-KEYWORD,1e100,✈️ ‍起飞
- DOMAIN-KEYWORD,abema,✈️ ‍起飞
- DOMAIN-KEYWORD,appledaily,✈️ ‍起飞
- DOMAIN-KEYWORD,avtb,✈️ ‍起飞
- DOMAIN-KEYWORD,beetalk,✈️ ‍起飞
- DOMAIN-KEYWORD,blogspot,✈️ ‍起飞
- DOMAIN-KEYWORD,dropbox,✈️ ‍起飞
- DOMAIN-KEYWORD,facebook,✈️ ‍起飞
- DOMAIN-KEYWORD,fbcdn,✈️ ‍起飞
- DOMAIN-KEYWORD,github,✈️ ‍起飞
- DOMAIN-KEYWORD,gmail,✈️ ‍起飞
- DOMAIN-KEYWORD,google,✈️ ‍起飞
- DOMAIN-KEYWORD,instagram,✈️ ‍起飞
- DOMAIN-KEYWORD,porn,✈️ ‍起飞
- DOMAIN-KEYWORD,sci-hub,✈️ ‍起飞
- DOMAIN-KEYWORD,spotify,✈️ ‍起飞
- DOMAIN-KEYWORD,telegram,✈️ ‍起飞
- DOMAIN-KEYWORD,twitter,✈️ ‍起飞
- DOMAIN-KEYWORD,whatsapp,✈️ ‍起飞
- DOMAIN-KEYWORD,youtube,✈️ ‍起飞
- MATCH,🌐 ‍未知站点
`